[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
authors = [
    {name = "Alexander Birk", email = "alexander.birk@ki.uni-stuttgart.de"},
]
name = "jupyterhub_profile_tool"
version = "0.1.2.dev1"
description = "A Jupyterhub service that allows users to create, modify and delete Jupyterhub spawner profiles"
readme = "README.md"
license = "BSD-2-Clause"
license-files = ["LICENSE.txt"]
dependencies = [
    "jupyterhub>=1.5.1",
    "tornado",
    "schema",
]
requires-python = ">=3.9"
keywords = [
    "Jupyter",
    "Jupyterhub",
    "Service",
]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]

[project.scripts]
jupyterhub_profile_tool = "jupyterhub_profile_tool.profilemaker:main"
userprofileworker = "jupyterhub_profile_tool.userprofileworker:main"

[project.urls]
"Bug Reports" = "https://github.tik.uni-stuttgart.de/KI/jupyterhub-profile-tool/issues"
"Source" = "https://github.tik.uni-stuttgart.de/KI/jupyterhub-profile-tool"
"About Jupyterhub" = "http://jupyterhub.readthedocs.io/en/latest/"
"Jupyter Project" = "http://jupyter.org"
