import argparse
import json
import subprocess
import os
import sys
import binascii
import logging

from tornado import ioloop, web
from tornado.log import app_log, access_log, gen_log
from urllib.parse import urljoin
from schema import Schema, And, Or, Use, Regex, Optional, SchemaError

from traitlets import HasTraits, Int, Unicode, Tuple

from jupyterhub.services.auth import HubOAuthenticated, HubOAuthCallbackHandler


class DataError(Exception):
    """Blanket error class to cover different failure cases ProfileManager can find. In general, requests that end with this error
    had something wrong with the associated data and were safely discarded. ProfileManager will add a message to present to the user.
    """
    pass


class BaseProfileHandler(HubOAuthenticated, web.RequestHandler):
    """Base handler class for this program. Does the mixin of hub authentication, creates a ProfileManager instance in its prepare method."""

    @web.authenticated
    def prepare(self):
        self.manager_instance = ProfileManager(self.current_user["name"])


class ProfileMakerHandler(BaseProfileHandler):
    """Manage Profiles for JupyterHub wrapspawner"""

    # This is the same code as in ServiceProfilesSpawner.
    def _fmt_description(self, spawner, options):
        option_elements = [ f"{k[4:] if k.startswith('req_') else k}: {v}" for k, v in options.items() if v ]
        return f"{spawner} profile settings {', '.join(option_elements)}"

    def _prepare_profile(self, profile):
        try:
            spawner = profile["spawner"]
        except KeyError:
            # SlurmSpawner is considered the default spawner by ServiceProfilesSpawner, so it is our default here, too.
            spawner = "SlurmSpawner"
        # Signature for the profile info for rendering is
        # [0]: Human-readable description (from the DB)
        # [1]: Profile ID (auto-created consistent identifier, generated by ProfileManager)
        # [2]: Options description (auto-created by _fmt_description from profile options), shown to the user by hovering in the profile selection
        # [3]: Additional HTML options to add to the <option> element, generated here. Currently only used to select the first profile by default.
        return [ profile["description"], profile["profile_id"], self._fmt_description(spawner, profile["options"]), "" ]

    def initialize(self, prefix):
        self.prefix = prefix

    def get(self):
        profiles = self.manager_instance.get_all_profiles()
        profiles_for_render = [ self._prepare_profile(profile) for profile in profiles ]
        if len(profiles_for_render) == 0:
            profiles_for_render = [ ["No profiles found", "invalid", "No profiles. If you think this is an error, please contact administration.", ""] ]
        # Always mark the first profile in the list as the one to initialize as selected
        profiles_for_render[0][3] = "selected"
        self.render("page.html",
                    base_url="/hub/",
                    user=self.current_user["name"],
                    profiles=profiles_for_render,
                    prefix=self.prefix)

# POST action on this endpoint was used for testing only; permanently disable it for productive use.
#     def post(self):
#         spawner_options = {"req_nprocs": "1", "req_memory": "100M", "req_partition": "fastlane", "req_runtime": "00:10:00"}
#         profile = {"description": "Test profile", "options": spawner_options}
#         self.manager_instance.create_profile(profile)
#         self.write({"status": "OK"})


class ProfileGetAllHandler(BaseProfileHandler):
    """Gets all profiles of the user"""

    def get(self):
        try:
            profiles = self.manager_instance.get_all_profiles()
            self.write({"profiles": profiles})
        except DataError as e:
            self.set_status(404)
            self.write({"status": "error", "message": str(e)})


class ProfileGetHandler(BaseProfileHandler):
    """Gets the user's profiles"""

    def get(self, profile_id):
        try:
            profile = self.manager_instance.get_singular_profile(profile_id)
            self.write(profile)
        except DataError as e:
            self.set_status(404)
            self.write({"status": "error", "message": str(e)})


class ProfileCreateHandler(BaseProfileHandler):
    """Creates an entirely new profile for the current user"""

    def post(self):
        app_log.debug(f"Creating profile for user {self.current_user["name"]}.")
        data = self.request.body.decode("utf-8")
        try:
            self.manager_instance.create_profile(data)
            self.write({"status": "OK"})
        except (DataError) as e:
            self.set_status(400)
            self.write({"status": "error", "message": str(e)})


class ProfileUpdateHandler(BaseProfileHandler):
    """Updates a given profile for the current user"""

    def post(self, profile_id):
        app_log.debug(f"Updating profile {profile_id} for user {self.current_user["name"]}.")
        data = self.request.body.decode('utf-8')
        try:
            self.manager_instance.update_profile(profile_id, data)
            self.write({"status": "OK"})
        except DataError as e:
            self.set_status(400)
            self.write({"status": "error", "message": str(e)})


class ProfileDeleteHandler(BaseProfileHandler):
    """Removes a profile for the current user"""

    def post(self, profile_id):
        app_log.debug(f"Deleting profile {profile_id} for user {self.current_user["name"]}.")
        try:
            self.manager_instance.delete_profile(profile_id)
            self.write({"status": "OK"})
        except DataError as e:
            self.set_status(400)
            self.write({"status": "error", "message": str(e)})


class ProfileManager(HasTraits):
    """Performs the profile management in the background, keeping the Handlers simple
    Note on Interfaces: ProfileManager always returns payloads as Python objects including a string ID,
    but accepts both int and string IDs as well as Python object and string payloads.
    """

    class FileOpException(Exception):
        pass

    system_profile_path = Unicode(
        "/etc/jupyterhub/common_profiles.json",
        config=True
    )

    home_base_dir = Unicode(
        "/home/",
        config=True
    )

    allowed_partitions = Tuple(
        ("slowlane", "fastlane"),
        config=True
    )

    max_cpu_cores = Int(
        256,
        config=True
    )

    def __init__(self, username):
        app_log.debug(f"Instantiating profile manager for user {username}")
        self.__generate_schema()
        self.username = username
        self.user_profile_path = os.path.join(self.home_base_dir, username, ".jupyterhub", "user_profiles.json")

    def __profile_id_to_index(self, profile_id):
        if profile_id.startswith("userprof_"):
            return int(profile_id.strip("userprof_")), True
        elif profile_id.startswith("sysprof_"):
            return int(profile_id.strip("sysprof_")), False
        else:
            raise ValueError(f"{profile_id} does not look like a known profile ID")

    def __index_to_profile_id(self, index, user=True):
        return f"userprof_{index}" if user else f"sysprof_{index}"

    def __ensure_stringified(self, profile_in):
        if isinstance(profile_in, dict) or isinstance(profile_in, list):
            profile_out = json.dumps(profile_in)
        elif isinstance(profile_in, str):
            # If `profile_in` is a string already, use it as-is.
            profile_out = profile_in
        else:
            raise ValueError(f"Unexpected profile representation: {type(profile_in)}. Cannot continue.")
        return profile_out

    def __ensure_objectified(self, profile_in):
        if isinstance(profile_in, str):
            try:
                profile_out = json.loads(profile_in)
            except json.JSONDecodeError as e:
                app_log.error(f"Could not parse JSON entries in string. Reported JSON error: {e}")
                raise e
        elif isinstance(profile_in, dict) or isinstance(profile_in, list):
            # If `profile_in` is a python object already, use it as-is
            profile_out = profile_in
        else:
            raise ValueError(f"Unexpected profile representation: {type(profile_in)}. Cannot continue.")
        return profile_out

    def __generate_schema(self):
        """Creates a new profile_schema for the instance. Note: The schema must be created at runtime because it uses traitlets."""
        self.profile_schema = Schema(
            {
                "description": And(str, lambda s: (len(s)>0 and not s.isspace()), error="Description is not a string, empty or consists only of spaces"),
                Optional("profile_id"): str,
                Optional("spawner"): str,
                "options": {
                    "req_partition": Or(*self.allowed_partitions, error="Unknown partition"),
                    "req_runtime": Regex(r"^([0-9]-)?[0-9]{2}:[0-9]{2}:[0-9]{2}$", error="Malformed runtime specification"),
                    "req_nprocs": And(Use(str), lambda s: s.isdigit(), lambda s: (1 <= int(s) <= self.max_cpu_cores), error=f"Invalid nprocs spec, must be between 1 and {self.max_cpu_cores}"),
                    "req_memory": And(Regex(r"^[1-9][0-9]*\s*[kKmMgGtT]?[bB]?$", error="Malformed memory specification"), Use(lambda s: s.upper().replace(" ","").replace("B",""))),
                    Optional("req_gres"): Regex(r"^(gpu:((A40:)|(A100:))?[1-8])?$", error="Malformed GRES specification"),
                },
            }
        )

    def __sanitize(self, profile_in):
        profile_out = self.profile_schema.validate(profile_in)
        profile_out.pop("profile_id", None)
        return profile_out

    def __sanitize_list(self, profiles_in):
        profiles_out = []
        error_stash = []
        for element in profiles_in:
            try:
                profiles_out.append(self.__sanitize(element))
            except SchemaError as e:
                # In some contexts, a subset of profiles being malformed and silently discarded may be acceptable.
                # Therefore, we store the errors and continue, leaving it to the caller to decide if everything should be discarded or not.
                error_stash.append(e)
        return profiles_out, error_stash

    def __file_op(self, action, user=True, entry_index=None, new_profile=None):
        """Handles interactions with JSON profile files"""
        user_actions = ("read", "write", "delete", "update")
        system_actions = ("read")
        if user and action not in user_actions:
            raise ValueError(f"Allowed actions for user directory are {' '.join(user_actions)}.")
        elif not user and action not in system_actions:
            raise ValueError(f"Allowed actions for system directory are {' '.join(system_actions)}.")
        cmd = [
            sys.executable,
            "-m", "jupyterhub_profile_tool.userprofileworker",
            "--action", action,
            ]
        if user:
            cmd.extend(["--path", self.user_profile_path])
        else:
            cmd.extend(["--path", self.system_profile_path])
        if entry_index is not None:
            cmd.extend(["--entry_index", str(entry_index)])
        if new_profile is not None:
            cmd.append(new_profile)
        app_log.debug(f"Full command: {' '.join(cmd)}")
        subproc_result = subprocess.run(cmd, capture_output=True, text=True, user=self.username if user else None)
        # When reporting problems in the subproc, we assume a two-stage approach.
        # If it returns an RC > 0, we assume something went seriously wrong and error out.
        # If it has an error output, but no non-normal RC, we forward the message as a warning, but continue.
        if subproc_result.returncode > 0:
            app_log.error(f"Errors encountered in subprocess: {subproc_result.stderr}")
            raise self.FileOpException(rc=subproc_result.returncode, error_message=subproc_result.stderr)
        elif subproc_result.stderr != "":
            app_log.warning(f"Problems encountered in subprocess: {subproc_result.stderr}")
        if action == "read":
            app_log.debug(f"Full subprocess output: {subproc_result.stdout}")
            return subproc_result.stdout

    def __log_and_raise(self, msg):
        app_log.error(msg)
        raise DataError(msg)

    def _get_profiles(self, user=True):
        str_profiles = self.__file_op("read", user=user)
        try:
            profiles = self.__ensure_objectified(str_profiles)
        except json.JSONDecodeError as e:
            app_log.error(f"Loaded {'user' if user else 'system'} profiles could not be parsed as JSON. Returning empty list to not break anything.")
            profiles = []
        profiles, errors = self.__sanitize_list(profiles)
        if len(errors) > 0:
            app_log.error(f"Loaded {'user' if user else 'system'} profiles look partially malformed. Schema reports the following: {"\n".join(errors)}. Returning well-formed profiles only.")
        app_log.debug(f"{'User' if user else 'System'} profile data structure is {profiles}")
        for index, profile in enumerate(profiles):
            # No more need for type checking. __sanitize takes care of that.
            profile["profile_id"] = self.__index_to_profile_id(index, user)
        return profiles

    def create_profile(self, profile_in):
        try:
            profile_obj = self.__ensure_objectified(profile_in)
        except json.JSONDecodeError:
            self.__log_and_raise("New profile`s specs could not be parsed. Stopping without changes.")
        try:
            profile_obj = self.__sanitize(profile_obj)
        except SchemaError as e:
            self.__log_and_raise(f"Schema evaluation for new profile failed. Schema says `{e}`. Stopping to avoid damage.")
        profile_str = self.__ensure_stringified(profile_obj)
        self.__file_op("write", new_profile=profile_str)

    def update_profile(self, profile_id, new_profile_in):
        try:
            old_profile_index, user = self.__profile_id_to_index(profile_id)
        except ValueError as e:
            self.__log_and_raise("Profile ID invalid. Stopping without changes.")
        if not user:
            self.__log_and_raise("Tried to update a system profile. This should not be attempted. Refusing.")
        try:
            new_profile_obj = self.__ensure_objectified(new_profile_in)
        except json.JSONDecodeError as e:
            self.__log_and_raise("Updated profile`s specs could not be parsed. Stopping without changes.")
        try:
            new_profile_obj = self.__sanitize(new_profile_obj)
        except SchemaError as e:
            self.__log_and_raise(f"Schema evaluation for updated profile failed. Schema says `{e}`. Stopping to avoid damage.")
        new_profile_str = self.__ensure_stringified(new_profile_obj)
        try:
            self.__file_op("update", entry_index=old_profile_index, new_profile=new_profile_str)
        except self.FileOpException as e:
            if e.rc == 78:
                self.__log_and_raise(f"Profile index {old_profile_index} does not exist. Stopping without changes.")
            raise e

    def delete_profile(self, profile_id):
        try:
            old_profile_index, user = self.__profile_id_to_index(profile_id)
        except ValueError:
            self.__log_and_raise("Profile ID invalid. Stopping without changes.")
        if not user:
            self.__log_and_raise("Tried to delete a system profile. This should not be attempted. Refusing.")
        try:
            self.__file_op("delete", entry_index=old_profile_index)
        except self.FileOpException as e:
            if e.rc == 78:
                self.__log_and_raise(f"Profile index {old_profile_index} does not exist. Stopping without changes.")
            raise e

    def get_all_profiles(self):
        user_profiles = self._get_profiles(user=True)
        system_profiles = self._get_profiles(user=False)
        return user_profiles + system_profiles

    def get_singular_profile(self, profile_id):
        try:
            index, user = self.__profile_id_to_index(profile_id)
        except ValueError:
            self.__log_and_raise("Profile ID invalid.")
        profiles = self._get_profiles(user)
        try:
            return profiles[index]
        except IndexError:
            self.__log_and_raise(f"Index out of bounds. List length is {len(profiles)}, requested index is {index}.")


def main():
    args = parse_arguments()
    abspath = os.path.abspath(__file__)
    dname = os.path.dirname(abspath)
    os.chdir(dname)
    app_log.addHandler(logging.handlers.SysLogHandler("/dev/log"))
    if args["debug"]:
        app_log.setLevel("DEBUG")
        access_log.addHandler(logging.handlers.SysLogHandler("/dev/log"))
        access_log.setLevel("DEBUG")
        gen_log.addHandler(logging.handlers.SysLogHandler("/dev/log"))
        gen_log.setLevel("DEBUG")
    else:
        app_log.setLevel("INFO")
    app_log.info(f"Working directory: {os.getcwd()}")
    application = create_application(cmdline_args=args)
    application.listen(args["port"])
    ioloop.IOLoop.current().start()


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--cookie-secret-file",
        help="Location of JupyterHub's cookie secret",
        type=str,
        required=True,
    )
    parser.add_argument(
        "--home-base-dir",
        help="Absolute path to the home directory location. Users` homes are derived as home-base-dir/username.",
        type=str,
        required=True,
    )
    parser.add_argument(
        "--service-prefix",
        help="Application API prefix",
        default=os.environ.get("JUPYTERHUB_SERVICE_PREFIX", "/"),
        type=str,
    )
    parser.add_argument(
        "--port",
        help="Port for API to listen on",
        default=8003,
        type=int,
    )
    parser.add_argument(
        "--debug",
        help="Activate the debug logging level",
        action="store_true",
    )
    return vars(parser.parse_args())


def create_application(cmdline_args, **kwargs):
    with open(cmdline_args["cookie_secret_file"]) as f:
        text_secret = f.read().strip()
    cookie_secret = binascii.a2b_hex(text_secret)
    ProfileManager.home_base_dir = cmdline_args["home_base_dir"]
    prefix = cmdline_args["service_prefix"]
    app_log.debug(f"Using service prefix {prefix}")
    return web.Application([(prefix, ProfileMakerHandler, {"prefix": prefix}),
                            (urljoin(prefix, "profiles/data"), ProfileGetAllHandler),
                            (urljoin(prefix, "profiles/create"), ProfileCreateHandler),
                            (urljoin(prefix, "profiles/(userprof_[0-9]+)/data"), ProfileGetHandler),
                            (urljoin(prefix, "profiles/(sysprof_[0-9]+)/data"), ProfileGetHandler),
                            (urljoin(prefix, "profiles/(userprof_[0-9]+)/update"), ProfileUpdateHandler),
                            (urljoin(prefix, "profiles/(userprof_[0-9]+)/delete"), ProfileDeleteHandler),
                            (urljoin(prefix, "oauth_callback"), HubOAuthCallbackHandler),
                           ],
                           cookie_secret=cookie_secret,
                           template_path="templates",
                           login_url="/hub/login")
