import json
import subprocess
import os
import binascii
import logging

from tornado import ioloop, web
from tornado.log import app_log, access_log, gen_log
from urllib.parse import urljoin
from schema import Schema, And, Or, Use, Regex, Optional, SchemaError

from traitlets.config import Application, Configurable
from traitlets import Int, Unicode, Tuple, Bool

from jupyterhub.services.auth import HubOAuthenticated, HubOAuthCallbackHandler


aliases = {
    "config-file": "ProfileMaker.config_file",
    "port": "ProfileMaker.port",
    "service-prefix": "ProfileMaker.service_prefix",
    "cookie-secret-file": "ProfileMaker.cookie_secret_file",
    "home-base-dir": "ProfileManager.home_base_dir",
    "system-profile-path": "ProfileManager.system_profile_path",
}

flags = {
    "debug": (
        {"Application": {"log_level": logging.DEBUG}},
        "Set log level to logging.DEBUG (maximize logging output)",
    ),
    "create-config": (
        {"ProfileMaker": {"create_config_file": True}},
        "Create default config file overwriting the existing config, if any, and exit",
    ),
}


class DataError(Exception):
    """Blanket error class to cover different failure cases ProfileManager can find. In general, requests that end with this error
    had something wrong with the associated data and were safely discarded. ProfileManager will add a message to present to the user.
    """
    pass


class BaseProfileHandler(HubOAuthenticated, web.RequestHandler):
    """Base handler class for this program. Does the mixin of hub authentication, creates a ProfileManager instance in its prepare method."""

    def initialize(self, prof_mgr):
        self.manager_instance = prof_mgr

    @web.authenticated
    def _get_username(self):
        self.user = self.current_user["name"]

    def prepare(self):
        app_log.debug(f"Request headers: {dict(self.request.headers)}")
        self._get_username()


class ProfileMakerHandler(BaseProfileHandler):
    """Manage Profiles for JupyterHub wrapspawner"""

    # This is the same code as in ServiceProfilesSpawner.
    def _fmt_description(self, spawner, options):
        option_elements = [ f"{k[4:] if k.startswith('req_') else k}: {v}" for k, v in options.items() if v ]
        return f"{spawner} profile settings are {', '.join(option_elements)}"

    def _prepare_profile(self, profile):
        try:
            spawner = profile["spawner"]
        except KeyError:
            # SlurmSpawner is considered the default spawner by ServiceProfilesSpawner, so it is our default here, too.
            spawner = "SlurmSpawner"
        # Signature for the profile info for rendering is
        # [0]: Human-readable description (from the DB)
        # [1]: Profile ID (auto-created consistent identifier, generated by ProfileManager)
        # [2]: Options description (auto-created by _fmt_description from profile options), shown to the user by hovering in the profile selection
        # [3]: Additional HTML options to add to the <option> element, generated here. Currently only used to select the first profile by default.
        return [ profile["description"], profile["profile_id"], self._fmt_description(spawner, profile["options"]), "" ]

    def initialize(self, app, prof_mgr):
        self.app = app
        super().initialize(prof_mgr)

    def get(self):
        profiles = self.manager_instance.get_all_profiles(self.user)
        profiles_for_render = [ self._prepare_profile(profile) for profile in profiles ]
        if len(profiles_for_render) == 0:
            profiles_for_render = [ ["No profiles found", "invalid", "No profiles. If you think this is an error, please contact administration.", ""] ]
        # Always mark the first profile in the list as the one to initialize as selected
        profiles_for_render[0][3] = "selected"
        self.render("page.html",
                    base_url="/hub/",
                    user=self.current_user["name"],
                    profiles=profiles_for_render,
                    prefix=self.app.service_prefix,
                    allowed_partitions=self.app.allowed_partitions,
                    max_cpu_cores=self.app.max_cpu_cores,
                    allowed_time_regex=self.app.allowed_time_regex)


class ProfileGetAllHandler(BaseProfileHandler):
    """Gets all profiles of the user"""

    def get(self):
        try:
            profiles = self.manager_instance.get_all_profiles(self.user)
            self.write({"profiles": profiles})
        except DataError as e:
            self.set_status(404)
            self.write({"status": "error", "message": str(e)})


class ProfileGetHandler(BaseProfileHandler):
    """Gets the user's profiles"""

    def get(self, profile_id):
        try:
            profile = self.manager_instance.get_singular_profile(self.user, profile_id)
            self.write(profile)
        except DataError as e:
            self.set_status(404)
            self.write({"status": "error", "message": str(e)})


class ProfileCreateHandler(BaseProfileHandler):
    """Creates an entirely new profile for the current user"""

    def post(self):
        app_log.debug(f"Creating profile for user {self.user}.")
        data = self.request.body.decode("utf-8")
        try:
            self.manager_instance.create_profile(self.user, data)
            self.write({"status": "OK"})
        except (DataError) as e:
            self.set_status(400)
            self.write({"status": "error", "message": str(e)})


class ProfileUpdateHandler(BaseProfileHandler):
    """Updates a given profile for the current user"""

    def post(self, profile_id):
        app_log.debug(f"Updating profile {profile_id} for user {self.user}.")
        data = self.request.body.decode('utf-8')
        try:
            self.manager_instance.update_profile(self.user, profile_id, data)
            self.write({"status": "OK"})
        except DataError as e:
            self.set_status(400)
            self.write({"status": "error", "message": str(e)})


class ProfileDeleteHandler(BaseProfileHandler):
    """Removes a profile for the current user"""

    def post(self, profile_id):
        app_log.debug(f"Deleting profile {profile_id} for user {self.user}.")
        try:
            self.manager_instance.delete_profile(self.user, profile_id)
            self.write({"status": "OK"})
        except DataError as e:
            self.set_status(400)
            self.write({"status": "error", "message": str(e)})


class ProfileManager(Configurable):
    """Performs the profile management in the background, keeping the Handlers simple
    Note on Interfaces: ProfileManager always returns payloads as Python objects including a string ID,
    but accepts both int and string IDs as well as Python object and string payloads.
    """

    home_base_dir = Unicode(
        "/home/",
        help = "The base directory for all the users` homes. Used to find individual profile files. Must be identical to SlurmSpawner`s setting of the same name.",
        config = True
    )

    system_profile_path = Unicode(
        "/etc/jupyterhub/common_profiles.json",
        help = "Path to the JSON file containing the commonly configured profiles",
        config = True
    )

    class FileOpException(Exception):
        """Special Exception class to signal errors in user child processes"""

        def __init__(self, rc, em):
            self.rc = rc
            self.em = em

        def __str__(self):
            return f"FileOpException: {str(self.em)} (return code {str(self.rc)})"

    def __init__(self, app, config):
        app_log.debug(f"Instantiating profile manager")
        super().__init__(config=config)
        self.__generate_schema(app)

    def __profile_id_to_index(self, profile_id):
        if profile_id.startswith("userprof_"):
            return int(profile_id.strip("userprof_")), True
        elif profile_id.startswith("sysprof_"):
            return int(profile_id.strip("sysprof_")), False
        else:
            raise ValueError(f"{profile_id} does not look like a known profile ID")

    def __index_to_profile_id(self, index, user=True):
        return f"userprof_{index}" if user else f"sysprof_{index}"

    def __ensure_stringified(self, profile_in):
        if isinstance(profile_in, dict) or isinstance(profile_in, list):
            profile_out = json.dumps(profile_in)
        elif isinstance(profile_in, str):
            # If `profile_in` is a string already, use it as-is.
            profile_out = profile_in
        else:
            raise ValueError(f"Unexpected profile representation: {type(profile_in)}. Cannot continue.")
        return profile_out

    def __ensure_objectified(self, profile_in):
        if isinstance(profile_in, str):
            try:
                profile_out = json.loads(profile_in)
            except json.JSONDecodeError as e:
                app_log.error(f"Could not parse JSON entries in string. Reported JSON error: {e}")
                raise e
        elif isinstance(profile_in, dict) or isinstance(profile_in, list):
            # If `profile_in` is a python object already, use it as-is
            profile_out = profile_in
        else:
            raise ValueError(f"Unexpected profile representation: {type(profile_in)}. Cannot continue.")
        return profile_out

    def __generate_schema(self, app):
        """Creates a new profile_schema for the instance. Note: The schema must be created at runtime because it uses traitlets."""
        self.profile_schema = Schema(
            {
                "description": And(str, lambda s: (len(s)>0 and not s.isspace()), error="Description is not a string, empty or consists only of spaces"),
                Optional("profile_id"): str,
                Optional("spawner"): str,
                "options": {
                    "req_partition": Or(*app.allowed_partitions, error="Unknown or disallowed partition"),
                    "req_runtime": Regex(app.allowed_time_regex, error="Malformed runtime specification"),
                    "req_nprocs": And(Use(str), lambda s: s.isdigit(), lambda s: (1 <= int(s) <= app.max_cpu_cores), error=f"Invalid nprocs spec, must be between 1 and {app.max_cpu_cores}"),
                    "req_memory": And(Regex(r"^[1-9][0-9]*\s*[kKmMgGtT]?[bB]?$", error="Malformed memory specification"), Use(lambda s: s.upper().replace(" ","").replace("B",""))),
                    Optional("req_gres"): Regex(r"^(gpu:((A40:)|(A100:))?[1-8])?$", error="Malformed GRES specification"),
                },
            }
        )

    def __sanitize(self, profile_in):
        profile_out = self.profile_schema.validate(profile_in)
        profile_out.pop("profile_id", None)
        return profile_out

    def __sanitize_list(self, profiles_in):
        profiles_out = []
        error_stash = []
        for element in profiles_in:
            try:
                profiles_out.append(self.__sanitize(element))
            except SchemaError as e:
                # In some contexts, a subset of profiles being malformed and silently discarded may be acceptable.
                # Therefore, we store the errors and continue, leaving it to the caller to decide if everything should be discarded or not.
                error_stash.append(e)
        return profiles_out, error_stash

    def __file_op(self, username, action, usertype=True, entry_index=None, new_profile=None):
        """Handles interactions with JSON profile files"""
        user_profile_path = os.path.join(self.home_base_dir, username, ".jupyterhub", "user_profiles.json")
        user_actions = ("read", "write", "delete", "update")
        system_actions = ("read")
        if usertype and action not in user_actions:
            raise ValueError(f"Allowed actions for user directory are {' '.join(user_actions)}.")
        elif not usertype and action not in system_actions:
            raise ValueError(f"Allowed actions for system directory are {' '.join(system_actions)}.")
        cmd = [
            "userprofileworker",
            "--action", action,
            ]
        if usertype:
            cmd.extend(["--path", user_profile_path])
        else:
            cmd.extend(["--path", self.system_profile_path])
        if entry_index is not None:
            cmd.extend(["--entry_index", str(entry_index)])
        if new_profile is not None:
            cmd.append(new_profile)
        app_log.debug(f"Full command: {' '.join(cmd)}")
        subproc_result = subprocess.run(cmd, capture_output=True, text=True, user=username if usertype else None)
        # When reporting problems in the subproc, we assume a two-stage approach.
        # If it returns an RC > 0, we assume something went seriously wrong and error out.
        # If it has an error output, but no non-normal RC, we forward the message as a warning, but continue.
        if subproc_result.returncode > 0:
            app_log.error(f"Errors encountered in subprocess: {subproc_result.stderr}")
            raise self.FileOpException(rc=subproc_result.returncode, em=subproc_result.stderr)
        elif subproc_result.stderr != "":
            app_log.warning(f"Problems encountered in subprocess: {subproc_result.stderr}")
        if action == "read":
            app_log.debug(f"Full subprocess output: {subproc_result.stdout}")
            return subproc_result.stdout

    def __log_and_raise(self, msg):
        app_log.error(msg)
        raise DataError(msg)

    def _get_profiles(self, username, usertype=True):
        str_profiles = self.__file_op(username, "read", usertype=usertype)
        try:
            profiles = self.__ensure_objectified(str_profiles)
        except json.JSONDecodeError as e:
            app_log.error(f"Loaded {'user' if usertype else 'system'} profiles could not be parsed as JSON. Returning empty list to not break anything.")
            profiles = []
        profiles, errors = self.__sanitize_list(profiles)
        if len(errors) > 0:
            app_log.error(f"Loaded {'user' if usertype else 'system'} profiles look partially malformed. Schema reports the following: {'\n'.join([str(e) for e in errors])}. Returning well-formed profiles only.")
        app_log.debug(f"{'User' if usertype else 'System'} profile data structure is {profiles}")
        for index, profile in enumerate(profiles):
            # No more need for type checking. __sanitize takes care of that.
            profile["profile_id"] = self.__index_to_profile_id(index, usertype)
        return profiles

    def create_profile(self, username, profile_in):
        try:
            profile_obj = self.__ensure_objectified(profile_in)
        except json.JSONDecodeError:
            self.__log_and_raise("New profile`s specs could not be parsed. Stopping without changes.")
        try:
            profile_obj = self.__sanitize(profile_obj)
        except SchemaError as e:
            self.__log_and_raise(f"Schema evaluation for new profile failed. Schema says `{e}`. Stopping to avoid damage.")
        profile_str = self.__ensure_stringified(profile_obj)
        self.__file_op(username, "write", new_profile=profile_str)

    def update_profile(self, username, profile_id, new_profile_in):
        try:
            old_profile_index, user = self.__profile_id_to_index(profile_id)
        except ValueError as e:
            self.__log_and_raise("Profile ID invalid. Stopping without changes.")
        if not user:
            self.__log_and_raise("Tried to update a system profile. This should not be attempted. Refusing.")
        try:
            new_profile_obj = self.__ensure_objectified(new_profile_in)
        except json.JSONDecodeError as e:
            self.__log_and_raise("Updated profile`s specs could not be parsed. Stopping without changes.")
        try:
            new_profile_obj = self.__sanitize(new_profile_obj)
        except SchemaError as e:
            self.__log_and_raise(f"Schema evaluation for updated profile failed. Schema says `{e}`. Stopping to avoid damage.")
        new_profile_str = self.__ensure_stringified(new_profile_obj)
        try:
            self.__file_op(username, "update", entry_index=old_profile_index, new_profile=new_profile_str)
        except self.FileOpException as e:
            if e.rc == 78:
                self.__log_and_raise(f"Profile index {old_profile_index} does not exist. Stopping without changes.")
            raise e

    def delete_profile(self, username, profile_id):
        try:
            old_profile_index, user = self.__profile_id_to_index(profile_id)
        except ValueError:
            self.__log_and_raise("Profile ID invalid. Stopping without changes.")
        if not user:
            self.__log_and_raise("Tried to delete a system profile. This should not be attempted. Refusing.")
        try:
            self.__file_op(username, "delete", entry_index=old_profile_index)
        except self.FileOpException as e:
            if e.rc == 78:
                self.__log_and_raise(f"Profile index {old_profile_index} does not exist. Stopping without changes.")
            raise e

    def get_all_profiles(self, username):
        user_profiles = self._get_profiles(username, usertype=True)
        system_profiles = self._get_profiles(username, usertype=False)
        return user_profiles + system_profiles

    def get_singular_profile(self, username, profile_id):
        try:
            index, usertype = self.__profile_id_to_index(profile_id)
        except ValueError:
            self.__log_and_raise("Profile ID invalid.")
        profiles = self._get_profiles(username, usertype)
        try:
            return profiles[index]
        except IndexError:
            self.__log_and_raise(f"Index out of bounds. List length is {len(profiles)}, requested index is {index}.")


class ProfileMaker(Application):

    name = "ProfileMaker"

    description = """A JupyterHub service and web app to enable users to customize their profiles for use with WrapSpawner."""

    aliases = aliases
    flags = flags
    classes = [ProfileManager]

    create_config_file = Bool(
        False,
        help = "Creates the service`s default config file and exits. WARNING: If set to True, overwrites `config_file` without notice.",
        config = True
    )

    config_file = Unicode(
        "profilemaker_config.py",
        help = "The main configuration file for this application",
        config = True
    )

    debug = Bool(
        True,
        help = "Run ProfileMaker in debug mode",
        config = True
    )

    cookie_secret_file = Unicode(
        "/root/.jupyterhub_secrets/jupyterhub_cookie_secret",
        help = "Path to the file containing JupyterHub`s shared cookie secret. Must be identical to JupyterHub`s setting of the same name.",
        config = True
    )

    port = Int(
        8003,
        help = "The local port that the profile maker tool should be running on",
        config = True
    )

    service_prefix = Unicode(
        "/services/jupyterhub_profile_tool/",
        help = "The web address prefix that this service will be running under",
        config = True
    )

    allowed_partitions = Tuple(
        ('fastlane', 'arboghast'),
        help = "Tuple of selectable partitions in the Profile Manager",
        config = True
    )

    max_cpu_cores = Int(
        256,
        help = "Amount of CPU cores to assign at maximum",
        config = True
    )

    allowed_time_regex = Unicode(
        "^([01]-)?([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$",
        help = "The regex a wall time specifier will be checked against",
        config = True
    )

    def create_webapp(self):
        with open(self.cookie_secret_file) as f:
            text_secret = f.read().strip()
        cookie_secret = binascii.a2b_hex(text_secret)
        profile_manager = ProfileManager(app=self, config=self.config)
        self.log.debug(f"Using service prefix {self.service_prefix}")
        self.log.info(f"Working directory: {os.getcwd()}")
        webapp = web.Application(
            [(self.service_prefix, ProfileMakerHandler, {"app": self, "prof_mgr": profile_manager}),
             (urljoin(self.service_prefix, "profiles/data"), ProfileGetAllHandler, {"prof_mgr": profile_manager}),
             (urljoin(self.service_prefix, "profiles/create"), ProfileCreateHandler, {"prof_mgr": profile_manager}),
             (urljoin(self.service_prefix, "profiles/(userprof_[0-9]+)/data"), ProfileGetHandler, {"prof_mgr": profile_manager}),
             (urljoin(self.service_prefix, "profiles/(sysprof_[0-9]+)/data"), ProfileGetHandler, {"prof_mgr": profile_manager}),
             (urljoin(self.service_prefix, "profiles/(userprof_[0-9]+)/update"), ProfileUpdateHandler, {"prof_mgr": profile_manager}),
             (urljoin(self.service_prefix, "profiles/(userprof_[0-9]+)/delete"), ProfileDeleteHandler, {"prof_mgr": profile_manager}),
             (urljoin(self.service_prefix, "oauth_callback"), HubOAuthCallbackHandler),
            ],
            cookie_secret=cookie_secret,
            template_path="templates",
            login_url="/hub/login"
        )
        webapp.log = self.log
        webapp.listen(self.port)
        ioloop.IOLoop.current().start()

    def write_config_file(self):
        """Write our default config to a .py config file"""
        config_file_dir = os.path.dirname(os.path.abspath(self.config_file))
        if not os.path.isdir(config_file_dir):
            self.exit(
                f"{config_file_dir} does not exist. The destination directory must exist before generating config file."
            )
        config_text = self.generate_config_file()
        if isinstance(config_text, bytes):
            config_text = config_text.decode('utf8')
        print(f"Writing default config to {self.config_file}")
        with open(self.config_file, mode='w') as f:
            f.write(config_text)

    def start(self):
        if self.create_config_file:
            self.write_config_file()
        else:
            self.load_config_file(self.config_file)
            self.create_webapp()

    def initialize(self, argv):
        self.log = logging.getLogger("tornado.application")
        self.parse_command_line(argv)
        self.log.debug("Traitlets initialized")
